pretrained_encoder_path: models/mles_model.p
# fold_list:
#   _target_: embeddings_validation.get_fold_list
#   config_path: conf/embeddings_validation_baselines_supervised.yaml

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: torch.load
    f: ${pretrained_encoder_path}
  head:
    _target_: ptls.nn.head.Head
    input_size: 1024
    hidden_layers_sizes: [512, 512]
    objective: classification
    num_classes: 1

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.supervised.seq_to_target_dataset.SeqToTargetIterableDataset
    target_col_name: flag
    # target_dtype: long
    data:
      _target_: ptls.data_load.datasets.AugmentationIterableDataset
      f_augmentations:
        - _target_: ptls.data_load.augmentations.RandomSlice
          min_len: 250
          max_len: 350
          rate_for_min: 0.9
        - _target_: ptls.data_load.augmentations.DropoutTrx
          trx_dropout: 0.01
      data:
        _target_: ptls.data_load.datasets.ParquetDataset
        i_filters:
          - _target_: ptls.data_load.iterable_processing.IdFilterDf
            df_relevant_ids:
              _target_: embeddings_validation.get_fold_ids
              config_path: conf/embeddings_validation_baselines_supervised.yaml
              kind: train
              fold_id: ${fold_id}
        data_files:
          _target_: ptls.data_load.datasets.parquet_file_scan
          file_path: data/train_trx.parquet
  valid_data:
    _target_: ptls.frames.supervised.seq_to_target_dataset.SeqToTargetDataset
    target_col_name: flag
    # target_dtype: long
    data:
      _target_: ptls.data_load.datasets.MemoryMapDataset
      data:
        _target_: ptls.data_load.datasets.ParquetDataset
        i_filters:
          - _target_: ptls.data_load.iterable_processing.IdFilterDf
            df_relevant_ids:
              _target_: embeddings_validation.get_fold_ids
              config_path: conf/embeddings_validation_baselines_supervised.yaml
              kind: valid
              fold_id: ${fold_id}
          - _target_: ptls.data_load.iterable_processing.ISeqLenLimit
            max_seq_len: 1200
        data_files:
          _target_: ptls.data_load.datasets.parquet_file_scan
          file_path: data/train_trx.parquet
  test_data:
    _target_: ptls.frames.supervised.seq_to_target_dataset.SeqToTargetDataset
    target_col_name: flag
    # target_dtype: long
    data:
      _target_: ptls.data_load.datasets.MemoryMapDataset
      data:
        _target_: ptls.data_load.datasets.ParquetDataset
        i_filters:
          - _target_: ptls.data_load.iterable_processing.ISeqLenLimit
            max_seq_len: 1200
        data_files:
          _target_: ptls.data_load.datasets.parquet_file_scan
          file_path: data/test_trx.parquet
  train_batch_size: 32
  train_num_workers: 16
  valid_batch_size: 64
  valid_num_workers: 8
  train_drop_last: true

